CREATE TABLE `joomla15`.`jos_mat_profile` (
  `id` INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
  `userid` VARCHAR(50) NOT NULL DEFAULT '',
  `pcby` VARCHAR(45) NOT NULL DEFAULT '',
  `gender` VARCHAR(20) NOT NULL DEFAULT '',
  `mstatus` VARCHAR(20) NOT NULL DEFAULT '',
  `weight` VARCHAR(30) NOT NULL DEFAULT '',
   `age` VARCHAR(30) NOT NULL DEFAULT '',
  `bodytype` VARCHAR(45) NOT NULL DEFAULT '',
  `complexion` VARCHAR(45) NOT NULL DEFAULT '',
  `height` VARCHAR(30) NOT NULL DEFAULT '',
  `mothertongue` VARCHAR(45) NOT NULL DEFAULT '',
  `community` VARCHAR(50) NOT NULL DEFAULT '',
  `zodic` VARCHAR(20) NOT NULL DEFAULT '',
  `manglik` VARCHAR(20) NOT NULL DEFAULT '',
  `education` VARCHAR(45) NOT NULL DEFAULT '',
  `specificdegree` VARCHAR(200) NOT NULL DEFAULT '',
  `profession` VARCHAR(100) NOT NULL DEFAULT '',
  `monthlyincome` VARCHAR(100) NOT NULL DEFAULT '',
  `familyvalue` VARCHAR(45) NOT NULL DEFAULT '',
  `diet` VARCHAR(20) NOT NULL DEFAULT '',
  `smoke` VARCHAR(20) NOT NULL DEFAULT '',
  `drink` VARCHAR(20) NOT NULL DEFAULT '',
  `bloodgroup` VARCHAR(10) NOT NULL DEFAULT '',
  `hobbies` VARCHAR(200) NOT NULL DEFAULT '',
  `about` TEXT NOT NULL,
  `location` VARCHAR(100) NOT NULL DEFAULT '',
  `city` VARCHAR(25) NOT NULL DEFAULT '',
  `state` VARCHAR(25) NOT NULL DEFAULT '',
  `phone` VARCHAR(50) NOT NULL DEFAULT '',
  `mobile` VARCHAR(50) NOT NULL DEFAULT '',
  `image` VARCHAR(200) NOT NULL DEFAULT '',
  `lfheight1` VARCHAR(50) NOT NULL DEFAULT '',
  `lfheight2` VARCHAR(50) NOT NULL DEFAULT '',
  `lfage1` VARCHAR(10) NOT NULL DEFAULT '',
  `lfage2` VARCHAR(45) NOT NULL DEFAULT '',
  `lfmstatus` VARCHAR(50) NOT NULL DEFAULT '',
  `lfcommunity` VARCHAR(50) NOT NULL DEFAULT '',
  `lfmothertongue` VARCHAR(50) NOT NULL DEFAULT '',
  `lfmanglik` VARCHAR(50) NOT NULL DEFAULT '',
  `lfprofession` VARCHAR(100) NOT NULL DEFAULT '',
  `lfcomplexion` VARCHAR(45) NOT NULL DEFAULT '',
  `lfotherrequirement` TEXT ,
  `params` TEXT NOT NULL,
  `ordering` INTEGER UNSIGNED NOT NULL DEFAULT 0,
  `hits` INTEGER UNSIGNED NOT NULL DEFAULT 0,
  `published` INTEGER UNSIGNED NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`)
)
ENGINE = InnoDB
CHARACTER SET utf8 COLLATE utf8_general_ci;
