CREATE TABLE `joomla15`.`jos_blog_user` (
  `id` INTEGER UNSIGNED NOT NULL DEFAULT NULL AUTO_INCREMENT,
  `userid` VARCHAR(50) NOT NULL DEFAULT '',
  `username` VARCHAR(50) NOT NULL DEFAULT '',
  `password` VARCHAR(100) NOT NULL DEFAULT '',
  `emailid` VARCHAR(200) NOT NULL DEFAULT '',
  `activation` VARCHAR(100) NOT NULL DEFAULT '',
  `registrationdate` DATETIME NOT NULL DEFAULT '0000-00-00 00:00:00',
  `lastvisitdate` DATETIME NOT NULL DEFAULT '0000-00-00 00:00:00',
  `addedbyip` VARCHAR(50) NOT NULL DEFAULT '',
  `lastvisitip` VARCHAR(50) NOT NULL DEFAULT '',
  `location` VARCHAR(100) NOT NULL DEFAULT '',
  `city` VARCHAR(25) NOT NULL DEFAULT '',
  `state` VARCHAR(25) NOT NULL DEFAULT '',
  `image` VARCHAR(100) NOT NULL DEFAULT '',
  `params` TEXT NOT NULL,
  `published` TINYINT(1) UNSIGNED NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`)
)
ENGINE = InnoDB
CHARACTER SET utf8 COLLATE utf8_general_ci;
