CREATE TABLE `joomla15`.`jos_mat_msg` (
  `id` INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
  `sender` VARCHAR(100) NOT NULL DEFAULT '',
  `receiver` VARCHAR(100) NOT NULL DEFAULT '',
  `title` VARCHAR(50) NOT NULL DEFAULT '',
  `msg` TEXT NOT NULL,
  `sdate` DATETIME NOT NULL DEFAULT '0000-00-00 00:00:00',
  `ipaddress` VARCHAR(45) NOT NULL DEFAULT '',
  `params` TEXT NOT NULL,
  `ordering` INTEGER UNSIGNED NOT NULL DEFAULT 0,
  `read` TINYINT(1) UNSIGNED NOT NULL DEFAULT 0,
  `published` TINYINT(1) UNSIGNED NOT NULL DEFAULT 1,
  PRIMARY KEY (`id`)
)
ENGINE = InnoDB
CHARACTER SET utf8 COLLATE utf8_general_ci;
