CREATE TABLE `joomla15`.`jos_sn_scrap` (
  `id` INTEGER UNSIGNED NOT NULL DEFAULT NULL AUTO_INCREMENT,
  `sender` VARCHAR(50) NOT NULL DEFAULT '',
  `recevier` VARCHAR(50) NOT NULL DEFAULT '',
  `scrap` TEXT NOT NULL,
  `sdate` DATETIME NOT NULL DEFAULT '0000-00-00 00:00:00',
  `private_scrap` TINYINT UNSIGNED NOT NULL DEFAULT 0,
  `params` TEXT NOT NULL,
  `published` TINYINT UNSIGNED NOT NULL DEFAULT 1,
  PRIMARY KEY (`id`)
)
ENGINE = InnoDB
CHARACTER SET utf8 COLLATE utf8_general_ci;