CREATE TABLE `dev_codefile` (
  `id` INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
  `category` VARCHAR(100) NOT NULL DEFAULT '',
  `title` VARCHAR(100) NOT NULL DEFAULT '',
  `description` TEXT NOT NULL,
  `codefile` VARCHAR(100) NOT NULL DEFAULT '',
  `creationdate` DATETIME NOT NULL DEFAULT '0000-00-00 00:00:00',
  `addedby` VARCHAR(20) NOT NULL DEFAULT '',
  `params` TEXT NOT NULL,
  `checked_out` INTEGER UNSIGNED NOT NULL DEFAULT 0,
  `checked_out_time` DATETIME NOT NULL DEFAULT '0000-00-00 00:00:00',  
  `hits` INTEGER UNSIGNED NOT NULL DEFAULT 0,
  `published` TINYINT(1) UNSIGNED NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`)
);
