CREATE TABLE `sn_ask_for_friendship` (
  `id` INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
  `asker` VARCHAR(50) NOT NULL DEFAULT '',
  `askfor` VARCHAR(50) NOT NULL DEFAULT '',
  `status` TINYINT(1) UNSIGNED NOT NULL DEFAULT 0,
  `rdate` DATETIME NOT NULL DEFAULT '0000-00-00 00:00:00',
  `params` TEXT NOT NULL,
  `published` TINYINT(1) UNSIGNED NOT NULL DEFAULT 1,
  PRIMARY KEY (`id`)
);
