CREATE TABLE `yellowpage` (
  `yid` INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
  `type` TEXT NOT NULL,
  `description` TEXT NOT NULL, 	
  `check_out` INTEGER UNSIGNED NOT NULL DEFAULT 0,
  `check_out_time` DATETIME NOT NULL DEFAULT '0000-00-00 00:00:00',
  `params` TEXT NOT NULL,
  `ordering` INTEGER UNSIGNED NOT NULL DEFAULT 0,
  `published` TINYINT(1) UNSIGNED NOT NULL DEFAULT 0,
  PRIMARY KEY (`yid`)
);