CREATE TABLE `yp_club` (
  `id` INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
  `yid` INTEGER UNSIGNED NOT NULL,
  `clubname` VARCHAR(50) NOT NULL DEFAULT '',
  `secretaryname` VARCHAR(50) NOT NULL DEFAULT '',
  `history` VARCHAR(200) NOT NULL DEFAULT '',
  `sportactivity` VARCHAR(200) NOT NULL DEFAULT '',
  `secretaryword` VARCHAR(200) NOT NULL DEFAULT '',
  `phone` VARCHAR(50) NOT NULL DEFAULT '',
  `mobile` VARCHAR(50) NOT NULL DEFAULT '',
  `location` VARCHAR(100) NOT NULL DEFAULT '',
  `city` VARCHAR(25) NOT NULL DEFAULT '',
  `state` VARCHAR(25) NOT NULL DEFAULT '',
  `emailid` VARCHAR(200) NOT NULL DEFAULT '',
  `website` VARCHAR(100) NOT NULL DEFAULT '',
  `description` TEXT NOT NULL,
  `checked_out` INTEGER UNSIGNED NOT NULL DEFAULT 0,
  `checked_out_time` DATETIME NOT NULL DEFAULT '0000-00-00 00:00:00',
  `params` TEXT NOT NULL,
  `odering` INTEGER UNSIGNED NOT NULL DEFAULT 0,
  `hits` INTEGER UNSIGNED NOT NULL DEFAULT 0,
  `published` TINYINT UNSIGNED NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
   CONSTRAINT `FK_yp_club` FOREIGN KEY `FK_yp_club` (`yid`)
    REFERENCES `yellowpage` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE
);